#!/usr/bin/env bash
# This script displays all listening TCP and UDP ports with PID and program name, like the project example

# Active Internet connections (TCP/UDP) only listening sockets
echo "Active Internet connections (only servers)"
sudo ss -tulnp

# Active UNIX domain sockets only listening
echo -e "\nActive UNIX domain sockets (only servers)"
sudo ss -xlp
